import enum


class JobState(enum.Enum):
    CREATED = "CREATED"
    FILE_UPLOAD_COMPLETED = "FILE_UPLOAD_COMPLETED"
    CONTAINER_FILES_BEING_EXTRACTED = "CONTAINER_FILES_BEING_EXTRACTED"
    CONTAINER_FILES_CREATED = "CONTAINER_FILES_CREATED"
    DOCKER_IMAGE_BEING_CREATED = "DOCKER_IMAGE_BEING_CREATED"
    DOCKER_IMAGE_CREATED = "DOCKER_IMAGE_CREATED"
    DOCKER_IMAGE_PUSHED = "DOCKER_IMAGE_PUSHED"
    ERROR = "ERROR"
